// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzwpo8Q_eVQkXfwNMc5BJstz-QYSNoGc4',
    appId: '1:553001438440:web:3dc029955bf8e34272cd5d',
    messagingSenderId: '553001438440',
    projectId: 'learnify-2a174',
    authDomain: 'learnify-2a174.firebaseapp.com',
    storageBucket: 'learnify-2a174.firebasestorage.app',
    measurementId: 'G-RNYPNTC09J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQN8429ZukMUUE9MBAO0J3FkASS8n1q8s',
    appId: '1:553001438440:android:dd999be879c15b8f72cd5d',
    messagingSenderId: '553001438440',
    projectId: 'learnify-2a174',
    storageBucket: 'learnify-2a174.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmBTeYZ2SM9eRElCHic6KisB5ITH-1J3o',
    appId: '1:553001438440:ios:3d447df582db3f3b72cd5d',
    messagingSenderId: '553001438440',
    projectId: 'learnify-2a174',
    storageBucket: 'learnify-2a174.firebasestorage.app',
    iosClientId: '553001438440-cuctq63q91esi088p96n0ca65cf280ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmBTeYZ2SM9eRElCHic6KisB5ITH-1J3o',
    appId: '1:553001438440:ios:3d447df582db3f3b72cd5d',
    messagingSenderId: '553001438440',
    projectId: 'learnify-2a174',
    storageBucket: 'learnify-2a174.firebasestorage.app',
    iosClientId: '553001438440-cuctq63q91esi088p96n0ca65cf280ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzwpo8Q_eVQkXfwNMc5BJstz-QYSNoGc4',
    appId: '1:553001438440:web:988346a5173d30c972cd5d',
    messagingSenderId: '553001438440',
    projectId: 'learnify-2a174',
    authDomain: 'learnify-2a174.firebaseapp.com',
    storageBucket: 'learnify-2a174.firebasestorage.app',
    measurementId: 'G-BPBVPT6BNH',
  );
}
